import bundled from "../../assets/bank.json";
import { parseBankFile } from "@shared/lib/questions/bankFile";
import type { CategoryKey, Question } from "@shared/lib/questions/schema";
import { matchWeight, weightedSample } from "@shared/lib/quiz/engine";

/**
 * The bank that ships inside the APK, so the first question does not need a
 * connection (#18, the native half of the web's #17 bundled bank).
 *
 * The JSON is committed and generated by `npm run bundle:bank` from
 * `content/questions`, validated by the same `questionSchema` as every other
 * read of the bank. `npm run validate` fails when the committed file drifts, so
 * this cannot quietly be a different bank from the web's.
 *
 * It is imported rather than fetched, and that is the whole difference from
 * `src/lib/questions/fallback.ts`. The web serves `public/bank.json` from a
 * stable URL it can precache by name; a phone has no such URL, and reading a
 * packaged file would need `expo-file-system` plus an `expo-asset` handle to
 * fetch bytes that were already in the binary. Metro resolves the import at
 * bundle time and the OS has it on disk from install.
 *
 * `parseBankFile` is the shared reader, so a corrupt row is dropped here
 * exactly as it would be on the web. The cast is deliberate: the generated JSON
 * is `unknown` as far as this module is concerned, and the schema is the only
 * thing allowed to decide a row is real.
 */
let cached: Question[] | null = null;

/** The whole published content bank, in file order. Parsed once per launch. */
export function localBank(): Question[] {
  if (cached) return cached;
  cached = parseBankFile(bundled as unknown);
  return cached;
}

/** Published bank size, for the done list's "N in the training set" line. */
export function localBankSize(): number {
  return localBank().length;
}

/**
 * The server draw, reproduced on the device. `questions:draw` filters by
 * seen ids and category, then Elo-matches the page; this does exactly the same
 * thing with `weightedSample` — the same function the Convex query calls, for
 * the same reason the quiz lib is shared in the first place.
 *
 * Without this the app needs a connection for its *first* question, which is
 * the one case offline play is for. With it the quiz screen draws from Convex
 * while it can and from the bundle when it cannot, and the two paths are
 * indistinguishable to the player.
 */
export function drawLocal(opts: {
  seen: Set<string>;
  categories: Set<CategoryKey>;
  ratingHint: number;
  count: number;
}): Question[] {
  const pool = localBank().filter(
    (q) =>
      !opts.seen.has(q.id) &&
      (opts.categories.size === 0 || opts.categories.has(q.category)),
  );
  if (pool.length === 0) return [];
  return weightedSample(
    pool,
    pool.map((q) => matchWeight(q.difficulty, opts.ratingHint)),
    opts.count,
  );
}
